                    --World map
Tracker:AddLocations("locations/Overworld/locations.jsonc")
                    --Dungeons
Tracker:AddLocations("locations/Dungeons/Airs Rock/Exterior.jsonc")
Tracker:AddLocations("locations/Dungeons/Airs Rock/Interior.jsonc")
Tracker:AddLocations("locations/Dungeons/Anemos Inner Sanctum/Anemos Inner Sanctum.jsonc")
Tracker:AddLocations("locations/Dungeons/Ankohl Ruins/Ankohl Ruins.jsonc")
Tracker:AddLocations("locations/Dungeons/Aqua Rock/Exterior.jsonc")
Tracker:AddLocations("locations/Dungeons/Aqua Rock/Interior.jsonc")
Tracker:AddLocations("locations/Dungeons/Dehkan Plateau/Dehkan Plateau.jsonc")
Tracker:AddLocations("locations/Dungeons/Gabomba Catacombs/Gabomba Catacombs.jsonc")
Tracker:AddLocations("locations/Dungeons/Gabomba Statue/Gabomba Statue.jsonc")
Tracker:AddLocations("locations/Dungeons/Gaia Rock/Exterior.jsonc")
Tracker:AddLocations("locations/Dungeons/Gaia Rock/Interior.jsonc")
Tracker:AddLocations("locations/Dungeons/Gondowan Cliffs/Gondowan Cliffs.jsonc")
Tracker:AddLocations("locations/Dungeons/Islet Cave/Islet Cave.jsonc")
Tracker:AddLocations("locations/Dungeons/Izumo Ruins/Izumo Ruins.jsonc")
Tracker:AddLocations("locations/Dungeons/Jupiter Lighthouse/Jupiter Lighthouse.jsonc")
Tracker:AddLocations("locations/Dungeons/Kandorean Temple/Kandorean Temple.jsonc")
Tracker:AddLocations("locations/Dungeons/Kibombo Mountains/Kibombo Mountains.jsonc")
Tracker:AddLocations("locations/Dungeons/Lemurian Ship/Lemurian Ship.jsonc")
Tracker:AddLocations("locations/Dungeons/Madra Catacombs/Madra Catacombs.jsonc")
Tracker:AddLocations("locations/Dungeons/Magma Rock/Exterior.jsonc")
Tracker:AddLocations("locations/Dungeons/Magma Rock/Interior.jsonc")
Tracker:AddLocations("locations/Dungeons/Mars Lighthouse/Mars Lighthouse Lower.jsonc")
Tracker:AddLocations("locations/Dungeons/Mars Lighthouse/Mars Lighthouse Upper.jsonc")
Tracker:AddLocations("locations/Dungeons/Shrine of the Sea God/Shrine of the Sea God.jsonc")
Tracker:AddLocations("locations/Dungeons/Taopo Swamp/Taopo Swamp.jsonc")
Tracker:AddLocations("locations/Dungeons/Treasure Isle/Treasure Isle.jsonc")
Tracker:AddLocations("locations/Dungeons/Tundaria Tower/Tundaria Tower.jsonc")
Tracker:AddLocations("locations/Dungeons/Yampi Desert/Yampi Desert.jsonc")
Tracker:AddLocations("locations/Dungeons/Yampi Desert Cave/Yampi Desert Cave.jsonc")
                    --Towns
Tracker:AddLocations("locations/Towns/Alhafra/Alhafra.jsonc")
Tracker:AddLocations("locations/Towns/Apojii Islands/Apojii Islands.jsonc")
Tracker:AddLocations("locations/Towns/Champa/Champa.jsonc")
Tracker:AddLocations("locations/Towns/Contigo/Contigo.jsonc")
Tracker:AddLocations("locations/Towns/Daila/Daila.jsonc")
Tracker:AddLocations("locations/Towns/Garoh/Garoh.jsonc")
Tracker:AddLocations("locations/Towns/Izumo/Izumo.jsonc")
Tracker:AddLocations("locations/Towns/Kibombo/Kibombo.jsonc")
Tracker:AddLocations("locations/Towns/Lemuria/Lemuria.jsonc")
Tracker:AddLocations("locations/Towns/Loho/Loho.jsonc")
Tracker:AddLocations("locations/Towns/Madra/Madra.jsonc")
Tracker:AddLocations("locations/Towns/Mikasalla/Mikasalla.jsonc")
Tracker:AddLocations("locations/Towns/Naribwe/Naribwe.jsonc")
Tracker:AddLocations("locations/Towns/Prox/Prox.jsonc")
Tracker:AddLocations("locations/Towns/Shaman Village/Shaman Village.jsonc")
Tracker:AddLocations("locations/Towns/Yallam/Yallam.jsonc")
